### ISSUE TITLE
Add feature to unblock users using their id and using mention

### ISSUE THREAD

**Issue by ChillNotTaken** [Cyanic76/discord-modmail#10]
pls add a feature where u could unblock people outside ticket cuz i blocked a user in ticket and ticket got delete so now i can t unblock him so plss also if u can add a block timer like !block @user (timer) (reason) and if u can then can u make like a logger like messages in ticket gets logged thanks

**Comment by Cyanic76** [comment]
Thanks for reporting this bug! You're now able to [unblock them from anywhere, unless you don't have the moderator/support team role](https://github.com/Cyanic76/discord-modmail/commit/9a7dd8050db044c9a92d44a0513f68cb377b64d1). The timer feature will be added soon too.

**Comment by ChillNotTaken** [comment]
Can you also add a feature to unpause users from anywhere cuz many of my
members got blocked with the unpause thing and what about the logs I said?
Thanks man appreciate your fast response
