### ISSUE TITLE
Issue When Messaging the Bot

### ISSUE THREAD

**Issue by ItsDeedaya** [Cyanic76/discord-modmail#13]
I'm getting an error message when I try and DM the bot, this doesn't happen on startup, only when I actually DM the bot

```
(node:74521) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'get' of undefined
    at Client.<anonymous> (/Users/evandeede/Downloads/discord-modmail/bot.js:18:30)
    at Client.emit (events.js:327:22)
    at MessageCreateAction.handle (/Users/evandeede/Downloads/discord-modmail/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/Users/evandeede/Downloads/discord-modmail/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/Users/evandeede/Downloads/discord-modmail/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/Users/evandeede/Downloads/discord-modmail/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/Users/evandeede/Downloads/discord-modmail/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/Users/evandeede/Downloads/discord-modmail/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/Users/evandeede/Downloads/discord-modmail/node_modules/ws/lib/websocket.js:825:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:74521) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:74521) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Cyanic76** [comment]
I'll look into this

**Comment by Cyanic76** [comment]
While I'm looking into this, could you copy and paste the line 18 here?

**Comment by Cyanic76** [comment]
Is the bug fixed?

**Comment by Cyanic76** [comment]
could you copy the [new](https://github.com/Cyanic76/discord-modmail/commit/bbc23e3f0663863f8a16a3ef74dbeaee65980c7d) bot.js file and try again?

**Comment by ItsDeedaya** [comment]
> can you copy the [new](https://github.com/Cyanic76/discord-modmail/commit/bbc23e3f0663863f8a16a3ef74dbeaee65980c7d) bot.js file and try again?

now i'm getting an error when starting up the bot, the message is below:

`  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/build/better_sqlite3.node
 → /Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/build/Debug/better_sqlite3.node
 → /Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/build/Release/better_sqlite3.node
 → /Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/out/Debug/better_sqlite3.node
 → /Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/Debug/better_sqlite3.node
 → /Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/out/Release/better_sqlite3.node
 → /Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/Release/better_sqlite3.node
 → /Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/build/default/better_sqlite3.node
 → /Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/compiled/14.15.1/darwin/x64/better_sqlite3.node
 → /Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node
 → /Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node
 → /Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node
 → /Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/lib/binding/node-v83-darwin-x64/better_sqlite3.node
    at bindings (/Users/evandeede/Downloads/discord-modmail/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/lib/database.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/lib/index.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  tries: [
    '/Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/build/better_sqlite3.node',
    '/Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/build/Debug/better_sqlite3.node',
    '/Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/build/Release/better_sqlite3.node',
    '/Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/out/Debug/better_sqlite3.node',
    '/Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/Debug/better_sqlite3.node',
    '/Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/out/Release/better_sqlite3.node',
    '/Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/Release/better_sqlite3.node',
    '/Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/build/default/better_sqlite3.node',
    '/Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/compiled/14.15.1/darwin/x64/better_sqlite3.node',
    '/Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node',
    '/Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node',
    '/Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node',
    '/Users/evandeede/Downloads/discord-modmail/node_modules/better-sqlite3/lib/binding/node-v83-darwin-x64/better_sqlite3.node'
  ]
}`

**Comment by ItsDeedaya** [comment]
> can you copy the [new](https://github.com/Cyanic76/discord-modmail/commit/bbc23e3f0663863f8a16a3ef74dbeaee65980c7d) bot.js file and try again?

There are a bunch of small issues in the code that give me error messages when launching and idk how to fix them all

**Comment by Cyanic76** [comment]
I've added 2 commits, can you try again?

Related to #15

**Comment by ItsDeedaya** [comment]
> I've added 2 commits, can you try again?
> 
> Related to #15

Got a new error, I put it on a pastebin bcuz the error was very long: https://pastebin.com/BC9BaRdi

I've also been getting some errors saying "Unsupported Engine" when installing node.js, discord.js, and quick.db, I'm not sure if those relate (these errors had no affect on installation though)

**Comment by Cyanic76** [comment]
You can find help for the "Could not locate bindings file" [here](https://github.com/Cyanic76/discord-modmail/wiki/Errors).

**Comment by ItsDeedaya** [comment]
> You can find help for the "Could not locate bindings file" [here](https://github.com/Cyanic76/discord-modmail/wiki/Errors).
> 
> "Unsupported engine"warn could be related to the fact that the nodejs version is too old, I'll soon look into that

It works now! Thank you so much!

**Comment by Cyanic76** [comment]
Nice, anytime
