### ISSUE TITLE
I have 2 errors.

### ISSUE THREAD

**Issue by CruzSucksAtCoding** [Cyanic76/discord-modmail#15]
So I will be showing the line of code with the error. 

Number one is I get this error:
 "UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'send' of undefined" 
 
 And heres the code: 
 "channel.send(`${message.author.username} > ${whatWeWant}`);"

And idk what to do. 

Anyways, number two is this:
"UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined"

And heres the code:
"await dbTable.set(`supportChannel_${channel.id}`, message.author.id);"

It would be helpful if someone could help!

(And I get these whenever I dm the bot)

**Comment by Cyanic76** [comment]
Should be fixed
