### ISSUE TITLE
can't send empty message

### ISSUE THREAD

**Issue by Jeanm0** [Cyanic76/discord-modmail#2]
i get that error each time someone send a dm to the bot

**Comment by Cyanic76** [comment]
Can you provide a log of that error?

**Comment by Cyanic76** [comment]
This commit should fix the issue. Try to edit your code and see if that error still pops up.

**Comment by Cyanic76** [comment]
[This commit](https://github.com/Cyanic76/discord-modmail/commit/c9965c1d82052de4c0314ed2e3665bd61f90413f) fixes your issue.
