### ISSUE TITLE
Still cannot install better-sqlite3

### ISSUE THREAD

**Issue by JaedonLau** [Cyanic76/discord-modmail#20]
i've tried all the things that you gave but it ain't working

**Comment by Cyanic76** [comment]
Where is the installation failing? Can you remove the node_modules folder and type `npm install`?

**Comment by JaedonLau** [comment]
It Says repl.it package operation failed

**Comment by Cyanic76** [comment]
Learn more [here](https://replit.com/talk/learn/package-operation-failed/11008/129067) & [here](https://replit.com/talk/ask/What-does-Replit-Package-operation-failed-mean/37267). Apparently repl.it's package manager is working differently from basic/vanilla npm.
