### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by ItsSeaside** [Cyanic76/discord-modmail#21]
Hi,  

I would like to have a new feature that opens mail from the staff room for example prefix open DiscordID and it would open a ticket and send them a message saying You have received a correspondence from a staff member of the server name here please wait until they send another message. Along the lines of that, I hope to see this in the future!

**Comment by Cyanic76** [comment]
This will be added.
You'll have to manually enable this feature (see the next commit) in the config.json.

**Comment by ItsSeaside** [comment]
Okay Thank you!
