### ISSUE TITLE
Bot doesn't answer

### ISSUE THREAD

**Issue by GarchoTTV** [Cyanic76/discord-modmail#22]
Bot doesn't give any reply, I can recieve the mod mail ticket entry but I can't answer

**Comment by GarchoTTV** [comment]
![image](https://user-images.githubusercontent.com/76499936/121884677-7e2ec880-cd13-11eb-933b-0820f67777bd.png)
this pop up when bot gets dm

**Comment by Cyanic76** [comment]
I don't have a bot.js file here. Did you rename index.js to bot.js?
Also if you don't use `replit.js` file, feel free to remove it.
