### ISSUE TITLE
Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by UsedSpxse** [Cyanic76/discord-modmail#23]
I am getting an error saying:
```
(node:520) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'send' of undefined
```
I tried uninstalling and reinstalling discord.js and it still errors out.
This is believed to be where it is erroring out.
```
      message.author.send(`Thanks for contacting the support team! We'll get back to you quickly.\nYour ticket ID is #${actualticket}.`)
      ```
      Please help!

**Comment by Cyanic76** [comment]
I believe it's a `client.channels.cache.get("...").send(...)` function doing this

**Comment by Cyanic76** [comment]
Hi, #23 author, can you test again?
