### ISSUE TITLE
Makes 2 channels every message & after 2nd time dming it starts not sending them in the category

### ISSUE THREAD

**Issue by InfinityDaGod** [Cyanic76/discord-modmail#25]
Hi, when I test the bot by dming it it makes two channels every message, after the 2nd time dming it starts to not send them in the category.

![](https://cdn.discordapp.com/attachments/746036818968969289/854720527607398410/unknown.png)

**Comment by Cyanic76** [comment]
Hi, I heard (via discord) you were using repl.it, is this right? If it is, read [this](https://github.com/Cyanic76/discord-modmail/wiki/Repl.it-users)

**Comment by InfinityDaGod** [comment]
no, I'm using glitch

**Comment by Cyanic76** [comment]
Maybe first of all use alphanumeric characters? There's no need to use special characters in username.

Remove the `replit.js` file as you dont need it.
