### ISSUE TITLE
dbTable & text not defined

### ISSUE THREAD

**Issue by DemonixDev** [Cyanic76/discord-modmail#26]
Hello the only thing that works is creating channel. The bot dont send user message, any command dont work (dbTable not found), if you dm multiple times it just keep create new ticket

**Comment by DemonixDev** [comment]
![Uploading 1624991487758..jpg…]()

**Comment by DemonixDev** [comment]
I get this when i DM bot

**Comment by DemonixDev** [comment]
Also permissions broken

**Comment by Cyanic76** [comment]
I can't help you: [your pic](https://github.com/Cyanic76/discord-modmail/issues/26#issuecomment-870822102) is broken.
If you're not using repl.it, delete the replit.js file.

**Comment by Cyanic76** [comment]
Also did you set correct role IDs?

**Comment by DemonixDev** [comment]
Yes, everything correct. And i deleted that file

**Comment by Cyanic76** [comment]
[This pic is broken](https://github.com/Cyanic76/discord-modmail/issues/26#issuecomment-870822102)

**Comment by DemonixDev** [comment]
Do you have discord? Will be easier for me

**Comment by Another-19** [comment]
ReferenceError: dbTable is not defined
     at Client.<anonymous> (/root/modmail/bot.js:110:17)
     at Client.emit (events.js:388:22)
     at MessageCreateAction.handle (/root/modmail/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
     at Object.module.exports [as MESSAGE_CREATE] (/root/modmail/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
     at WebSocketManager.handlePacket (/root/modmail/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
     at WebSocketShard.onPacket (/root/modmail/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
     at WebSocketShard.onMessage (/root/modmail/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
     at WebSocket.onMessage (/root/modmail/node_modules/ws/lib/event-target.js:132:16)
     at WebSocket.emit (events.js:376:20)
     at Receiver.receiverOnMessage (/root/modmail/node_modules/ws/lib/websocket.js:845:20)
     
 this error shows every time when user sent a message on a channel that is NOT a support channel

**Comment by Cyanic76** [comment]
Well, move the const to the top of the client.on function like you did

**Comment by DemonixDev** [comment]
Okay i will try.

**Comment by DemonixDev** [comment]
But i also have 

ReferenceError: text is not defined

**Comment by Cyanic76** [comment]
What line?

**Comment by Another-19** [comment]
```
Line 94 -  client.channels.cache.get(active.channelID).send(`${message.author.username} > ${text}`, {files: [message.attachments.first().url]})
Line 96 -  if(e) client.guilds.cache.get(config.guild).channels.cache.get(active.channelID).send(`${message.author.username} > ${text}`, {files: [message.attachments.first().url]})
Line 100 - client.channels.cache.get(active.channelID).send(`${message.author.username} > ${text}`);
Line 102 - if(e) client.guilds.cache.get(config.guild).channels.cache.get(active.channelID).send(`${message.author.username} > ${text}`)
```
You didn't define text to anything, and therefore it's returning undefined.
And also, you defined msg to message content. Line 84 - `     var msg = message.content;`
But it was never used. Maybe by changing `${text}` to `${msg}`?

**Comment by Cyanic76** [comment]
Should be fixed now.

**Comment by DmanAwesome1** [comment]
Hey so this isnt working too great. It doesnt start for me, even if I put everything in pls help

**Comment by DmanAwesome1** [comment]
Error: Cannot find module './config.json'
Require stack:
- /home/runner/AE-Modmail/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
internal/fs/utils.js:269
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/runner/AE-Modmail/index.js'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.<anonymous> (/run_dir/interp.js:195:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
internal/fs/utils.js:269
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/runner/AE-Modmail/index.js'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.<anonymous> (/run_dir/interp.js:195:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/runner/AE-Modmail/index.js'
}


**Comment by Cyanic76** [comment]
Are you using replit?

Download the index.js and config.json files again

**Comment by DmanAwesome1** [comment]
I am using replit. When I download all the files again it starts the process then dies immediately.

**Comment by DmanAwesome1** [comment]
And I did everything that you told replit users to do. What files do I need to remove exactly?

**Comment by DmanAwesome1** [comment]
What is your discord because the one on your website doesnt work

**Comment by Cyanic76** [comment]
> What files do I need to remove exactly?
You have to remove the `index.js`. Then, replace `index.js` by `replit.js` in the package.json at lines [5](https://github.com/Cyanic76/discord-modmail/blob/master/package.json#L5) and [7](https://github.com/Cyanic76/discord-modmail/blob/master/package.json#L7).

> What is your discord
[this](https://discord.gg/zp8zF7Zx7y)

**Comment by DmanAwesome1** [comment]
node v12.16.1
 

Replit: Updating package configuration

--> npm init -y
Wrote to /home/runner/AE-Modmail/package.json:

{
  "name": "AE-Modmail",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "chalk": "^4.1.1",
    "cors": "^2.8.5",
    "discord.js": "^12.5.3",
    "discord.js-commando": "^0.12.3",
    "express": "^4.17.1",
    "helmet": "^4.6.0",
Server {
  insecureHTTPParser: undefined,
  _events: [Object: null prototype] {
    request: [Function: app] EventEmitter {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      setMaxListeners: [Function: setMaxListeners],
      getMaxListeners: [Function: getMaxListeners],
      emit: [Function],
      addListener: [Function: addListener],
      on: [Function: addListener],
      prependListener: [Function: prependListener],
      once: [Function: once],
      prependOnceListener: [Function: prependOnceListener],
      removeListener: [Function: removeListener],
      off: [Function: removeListener],
      removeAllListeners: [Function: removeAllListeners],
      listeners: [Function: listeners],
      rawListeners: [Function: rawListeners],
      listenerCount: [Function: listenerCount],
      eventNames: [Function: eventNames],
      init: [Function: init],
      defaultConfiguration: [Function: defaultConfiguration],
      lazyrouter: [Function: lazyrouter],
      handle: [Function: handle],
      use: [Function: use],
      route: [Function: route],
      engine: [Function: engine],
      param: [Function: param],
      set: [Function: set],
      path: [Function: path],
      enabled: [Function: enabled],
      disabled: [Function: disabled],
      enable: [Function: enable],
      disable: [Function: disable],
      acl: [Function],
      bind: [Function],
      checkout: [Function],
      connect: [Function],
      copy: [Function],
      delete: [Function],
      get: [Function],
      head: [Function],
      link: [Function],
      lock: [Function],
      'm-search': [Function],
      merge: [Function],
      mkactivity: [Function],
      mkcalendar: [Function],
      mkcol: [Function],
      move: [Function],
      notify: [Function],
      options: [Function],
      patch: [Function],
      post: [Function],
      pri: [Function],
      propfind: [Function],
      proppatch: [Function],
      purge: [Function],
      put: [Function],
      rebind: [Function],
      report: [Function],
      search: [Function],
      source: [Function],
      subscribe: [Function],
      trace: [Function],
      unbind: [Function],
      unlink: [Function],
      unlock: [Function],
      unsubscribe: [Function],
      all: [Function: all],
      del: [Function],
      render: [Function: render],
      listen: [Function: listen],
      request: [IncomingMessage],
      response: [ServerResponse],
      cache: {},
      engines: {},
      settings: [Object],
      locals: [Object: null prototype],
      mountpath: '/',
      _router: [Function]
    },
    connection: [Function: connectionListener],
    listening: [Function: bound onceWrapper] { listener: [Function] }
  },
  _eventsCount: 3,
  _maxListeners: undefined,
  _connections: 0,
  _handle: TCP {
    reading: false,
    onconnection: [Function: onconnection],
    [Symbol(owner_symbol)]: [Circular]
  },
  _usingWorkers: false,
  _workers: [],
  _unref: false,
  allowHalfOpen: true,
  pauseOnConnect: false,
  httpAllowHalfOpen: false,
Hint: hit control+c anytime to enter REPL.
 

Replit: Updating package configuration

--> npm init -y
Wrote to /home/runner/AE-Modmail/package.json:

{
  "name": "AE-Modmail",
internal/fs/utils.js:269
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/runner/AE-Modmail/index.js'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.<anonymous> (/run_dir/interp.js:195:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/runner/AE-Modmail/index.js'
}

this is the error I get when I run it

**Comment by Cyanic76** [comment]
replace this
```"main": "index.js",```
with this
```"main": "replit.js",```

**Comment by DmanAwesome1** [comment]
> replace this
> `"main": "index.js",`
> with this
> `"main": "replit.js",`

Yeah I did that.

**Comment by Cyanic76** [comment]
What's the output?

**Comment by DmanAwesome1** [comment]
<img width="767" alt="Screen Shot 2021-07-07 at 10 27 46 AM" src="https://user-images.githubusercontent.com/81495408/124787269-fac95700-df0d-11eb-90da-60189bc678d5.png">
these are my files

**Comment by Cyanic76** [comment]
I'll ask you to cancel [these changes](https://github.com/Cyanic76/discord-modmail/issues/26#issuecomment-875700876) and rename `replit.js` to `index.js` file.

**Comment by DmanAwesome1** [comment]
> I'll ask you to cancel [these changes](https://github.com/Cyanic76/discord-modmail/issues/26#issuecomment-875700876) and rename `replit.js` to `index.js` file.

internal/fs/utils.js:269
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/runner/AE-Modmail/index.js'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.<anonymous> (/run_dir/interp.js:195:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/runner/AE-Modmail/index.js'
}


**Comment by Cyanic76** [comment]
index.js doesn't exist on your side.

**Comment by DmanAwesome1** [comment]
> index.js doesn't exist on your side.

I renamed replit.js to index.js

**Comment by Cyanic76** [comment]
In the package.json file, replace replit.js with index.js (there should be **2** occurences) and rename the main file to index.js.
