### ISSUE TITLE
table is not defined / userID is not defined

### ISSUE THREAD

**Issue by AngelIsSad** [Cyanic76/discord-modmail#29]
Everytime when i try closing an open support ticket, an error pops up saying `userID is not defined` and im not sure how to fix this

When replying to an open support ticket with `[prefix]reply`, there is an error saying table is not defined

![1](https://cdn.discordapp.com/attachments/799903961888849981/866619284578500638/unknown.png)

![2](https://cdn.discordapp.com/attachments/799903961888849981/866974863122235392/unknown.png)

**Comment by AngelIsSad** [comment]
dbTable2 is still not defined and the reply feature still doesn't work

**Comment by AngelIsSad** [comment]
Line: 111 and 112

**Comment by AngelIsSad** [comment]
Yes

**Comment by AngelIsSad** [comment]
The log broke now [Image](https://cdn.discordapp.com/attachments/799903961888849981/867002184490811392/unknown.png)

**Comment by AngelIsSad** [comment]
It logs messages which are not in embed, but doesnt log embed messages
[Image](https://cdn.discordapp.com/attachments/866598522781171723/867322555327971378/unknown.png)

**Comment by Cyanic76** [comment]
Try to put this [here](https://github.com/Cyanic76/discord-modmail/blob/master/bot.js#L218)
```js
for(var i = 0; i < msg.embeds.length; i++) {
  collection += `${msg.embeds[i].description}\n\n`;
}
```

**Comment by AngelIsSad** [comment]
It worked!

**Comment by AngelIsSad** [comment]
I have a question

**Comment by AngelIsSad** [comment]
Is it possible to make it like so when a user DMs the Bot, the Bot asks him some questions before creating a channel in the server?

In short: DM Menu

**Comment by AngelIsSad** [comment]
I found another bug

**Comment by Cyanic76** [comment]
You can do so using a [reaction menu](https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=awaitReactions) or an [awaitMessages](https://discord.js.org/#/docs/main/stable/class/DMChannel?scrollTo=awaitMessages) function.

**Comment by AngelIsSad** [comment]
The Bot creates the ticket channel on top of the server when Admin perms are denied but all other perms are enabled

**Comment by Cyanic76** [comment]
[Here](https://github.com/Cyanic76/discord-modmail/blob/master/bot.js#L40), directly put an ID like `channel.setParent('id');` instead of `config.ticketCategory`

**Comment by AngelIsSad** [comment]
It still creates the channel on top

**Comment by AngelIsSad** [comment]
[Image](https://cdn.discordapp.com/attachments/863400362182705202/867328043704647680/unknown.png)

**Comment by Cyanic76** [comment]
Do you see any error in the console?

**Comment by AngelIsSad** [comment]
Missing Permission and Missing Access

**Comment by AngelIsSad** [comment]
No line shown

**Comment by AngelIsSad** [comment]
[Error](https://cdn.discordapp.com/attachments/867327899584167937/867328613429936158/unknown.png)

**Comment by Cyanic76** [comment]
It's an error on your side

Check [this](https://stackoverflow.com/questions/64217395/discordapierror-missing-access-on-createoverwrite) and [this](https://stackoverflow.com/questions/62129936/unhandledpromiserejectionwarning-discordapierror-missing-permissions)
