### ISSUE TITLE
Massive Issue, nothink working...

### ISSUE THREAD

**Issue by MaximKing1** [Cyanic76/discord-modmail#3]
So I have setup the bot as it says in the config.json and touched nothink else done npm I to install and hosting on VPS, it creates the channel but I can’t use the commands like areply, complete, pause etc or when someone speaks at the bot it sends loads of Created Ticket 1, then will say 2 then 3 etc won’t reply to last ticket?

**Comment by Cyanic76** [comment]
Thanks for reporting this issue.

Do you have any log or error showing up in your npm console?

**Comment by MaximKing1** [comment]
So it don’t have any errors and did create a json.SQLite file which had data in it, the bot just made the channel and the description was working etc just commands or anything else weren’t ...

**Comment by MaximKing1** [comment]
@Cyanic76

**Comment by Cyanic76** [comment]
I pushed a commit recently.

**Comment by MaximKing1** [comment]
No I use a VPS server with 2GB memory

**Comment by MaximKing1** [comment]
@Cyanic76

**Comment by NotSure70** [comment]
can you show the error please?

**Comment by Cyanic76** [comment]
[There are no errors](https://github.com/Cyanic76/discord-modmail/issues/3#issuecomment-726351170) as far as I know.

I'm looking for a fix rn, but the thing is that I tested the code and put it on my personal bot, it does not seem to log any errors.

**Comment by Cyanic76** [comment]
Another question, does the json.sqlite file gets deleted or cleared?

**Comment by MaximKing1** [comment]
@Cyanic76 The json.sqlite file does not get cleared or deleted and the ticket does show a number.

**Comment by Cyanic76** [comment]
I pushed a [new commit](https://github.com/Cyanic76/discord-modmail/commit/a5629bb40bd591621d63d0d1767ba5452d168af9), can you download the code and try again to see if everything's working?

**Comment by Cyanic76** [comment]
The bug has been fixed.
