### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by patelom693** [Cyanic76/discord-modmail#34]
**npm start

Markdown

Q x

> discord-modmail@1.1.0 start /home/runner/

discord-modmail-1

> node bot.js

/home/runner/discord-modmail-1/bot.js:139

await client.channels.fetch(con fig.log).send({embeds: [newTicketLog]});

SyntaxError: await is only valid in async f unction**

at wrapSafe (internal/modules/cjs/loade r.js:915:16)

at Module_compile (internal/modules/cj

s/loader.js:963:27) at Object.Module. _extensions..js (inter

nal/modules/cjs/loader.js:1027:10)

at Module.load (internal/modules/cjs/lo

ader.js:863:32)

at Function.Module. load (internal/modu

les/cjs/loader.js:708:14)

at Function.executeUserEntryPoint [as r unMain] (internal/modules/run_main.js:60:12

at internal/main/run_main_module.js:17:

47

**npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! discord-modmail@1.1.0 start: 'node bot.js'

npm ERR! Exit status 1

npm ERR! npm ERR! Failed at the discord-modmail@1.1.

0 start script.

npm ERR! This is probably not a problem wit h npm. There is likely additional logging o utput above.

npm ERR! A complete log of this run can be

found in:**

**Comment by Cyanic76** [comment]
This issue is fixed.
