### ISSUE TITLE
This is a duplicate of #34.

### ISSUE THREAD

**Issue by patelom693** [Cyanic76/discord-modmail#36]
How can I solve this problem?

**Comment by patelom693** [comment]
![Uploading Screenshot_2021-09-10-09-21-45-504_com.android.chrome.jpg…]()

**Comment by patelom693** [comment]
@Cyanic76 how can i solve this  problem?

**Comment by Cyanic76** [comment]
You've got no patience at all. Why close the issue within a hour? I couldn't even get the time to look into this before you closed the issue.
