### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by patelom693** [Cyanic76/discord-modmail#38]
Help me @Cyanic76 
![Screenshot](https://user-images.githubusercontent.com/84563189/132803492-67604f2c-2b80-432d-97c7-0874f4423033.jpg)

**Comment by Cyanic76** [comment]
Your screenshot is broken. Post it on imgur.

**Comment by Cyanic76** [comment]
> Paste your bot's token in the process.env file.
[Read the wiki](https://github.com/Cyanic76/discord-modmail/wiki/Installation).

**Comment by patelom693** [comment]
I already paste my token

**Comment by patelom693** [comment]
Showing this error

**Comment by Cyanic76** [comment]
There's an error in your client.login() function somewhere.
I'm trying to help you right now.

**Comment by patelom693** [comment]
Thanks  for  helping me
