### ISSUE TITLE
BUG: Probleme with channel permission and close

### ISSUE THREAD

**Issue by ZyGout** [Cyanic76/discord-modmail#4]
**Describe the bug**

Not every times, everyone have acces to the channel or i can't close the ticket.

**To reproduce**

Not every times, everyone have acces to the channel or i can't close the ticket.

**Expected behavior**

No probleme, I always can close the ticket or the channel are always configurated.

**Your host**

I use repl.it with 512MB of RAM

**Comment by Cyanic76** [comment]
Seems like a permission is missing - 
Are you sure you gave the "Manage channels" permission to your bot?

**Comment by ZyGout** [comment]
Yes, it have the admin perm

**Comment by Cyanic76** [comment]
Okay, is it showing any error, warn or something in the console/logs?

**Comment by ZyGout** [comment]
Yes, "Cannot read property 'targetID' of null" when i want to close the ticket. And i have fix the bug with permission, do you want my code ?

**Comment by Cyanic76** [comment]
I've published a commit that modify where support.targetID. Can you try updating your code to see if it's fixed?

**Comment by ZyGout** [comment]
Ok, i have change the version and i will say you if i have the same probleme.
