### ISSUE TITLE
Supplied parameter is not a User nor a Role (dmUsers is true)

### ISSUE THREAD

**Issue by whiteewolf** [Cyanic76/discord-modmail#41]
i dm the bot when DmUsers in config is true
it throws this: `TypeError [INVALID_TYPE]: Supplied parameter is not a User nor a Role.`
idk where exactly is the problem in the code
im hosting on my pc for now

**Comment by Cyanic76** [comment]
Read #39

**Comment by Cyanic76** [comment]
Submit the error log. Please.

**Comment by Cyanic76** [comment]
Issue seems resolved.
