### ISSUE TITLE
[BUG]: [BUG NAME]TypeError: Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by AnonymousCoder69420** [Cyanic76/discord-modmail#9]
I was working with this modmail bot, I added a few things of my own into it actually, and it said "TypeError: Cannot read property 'send' of undefined", so I figured I would just re-set it. But when i reset it, it didn't work and it still threw the same error at me. If you can fix this, I would be very thankful. I've looked at it and I just cant seem to find an issue with it.

**Comment by Cyanic76** [comment]
Where was the error you encountered? At which line?

**Comment by AnonymousCoder69420** [comment]
> Where was the error you encountered? At which line?

It didnt specify, lol. It just said:

(node:1125) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'send' of undefined
(node:1125) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

I really have no idea what to do

**Comment by Cyanic76** [comment]
Can you retry, please?

**Comment by AnonymousCoder69420** [comment]
> Can you retry, please?

What do you mean? Re-try copying the code? sure I can

**Comment by AnonymousCoder69420** [comment]
> Can you retry, please?

I re-copied it and now its telling me 
/home/runner/Dank-Utils/index.js:202
      return client.users.cache.get(support.targetID).("Hi! Your ticket isn't paused anymore. We're ready to continue!");
                                                      ^

SyntaxError: Unexpected token '('

Which is weird, because there needs to be a `(` right there, lol

**Comment by Cyanic76** [comment]
Can you put the 202nd line of your index.js file here?

**Comment by AnonymousCoder69420** [comment]
> Can you put the 202nd line of your index.js file here?

its   
`return client.users.cache.get(support.targetID).("Hi! Your ticket isn't paused anymore. We're ready to continue!");`

**Comment by Cyanic76** [comment]
Can you retry with [updated code](https://github.com/Cyanic76/discord-modmail/blob/27aff6b89253a0149e24c90cb11e8e6367481f92/bot.js) ?

**Comment by AnonymousCoder69420** [comment]
> Can you retry with [updated code](https://github.com/Cyanic76/discord-modmail/blob/27aff6b89253a0149e24c90cb11e8e6367481f92/bot.js) ?

(node:1646) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'send' of undefined
(node:1646) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1646) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Same thing as before ;-;

**Comment by Cyanic76** [comment]
I'll look into this and test things. I'll keep you updated!

**Comment by AnonymousCoder69420** [comment]
> I'll look into this and test things. I'll keep you updated!

Thank you for your help!

**Comment by Cyanic76** [comment]
One more question, did the error happened using a command, sending a message to the bot, ...?

**Comment by AnonymousCoder69420** [comment]
> One more question, did the error happened using a command, sending a message to the bot, ...?

Yes, right when I say "hello" or anything to the bot, it just sends that error in terminal.

**Comment by Cyanic76** [comment]
Can you try with that?

**Comment by AnonymousCoder69420** [comment]
> Can you try with that?

sure

**Comment by AnonymousCoder69420** [comment]
> Can you try with that?

Oof, still not working. Same issue, i've been trying at this for hours 😂

**Comment by AnonymousCoder69420** [comment]
> Can you try with that?

I'm going to try cloning the repo and seeing if it works on a separate bot.

**Comment by AnonymousCoder69420** [comment]
> Can you try with that?

THIS IS WEIRD! I cloned the repo to a different bot and now it works just fine, I have no idea whats going on!

**Comment by Cyanic76** [comment]
One question, have you looked into your config.json file?

**Comment by AnonymousCoder69420** [comment]
> One question, have you looked into your config.json file?

yes, same error no matter what in my bot, maybe I screwed something up in another part of my code thats causing this perhaps?

**Comment by AnonymousCoder69420** [comment]
> One question, have you looked into your config.json file?

Well thanks for your help, sorry if I wasted your time 😅 Its a great bot BTW, thanks for providing it here and being a good help to me.

**Comment by Cyanic76** [comment]
Thanks a lot for your feedback, appreciate it!
